💂‍♀️ Add guard based on ReactElement
MOZGIII/tagged-state pull request #2
Opened 2022-07-07 09:54 UTC by sesh92

Allow using tagged state via Guard based on ReactElement

```
<Guard
  uninit={<UninitComponent />}
  ready={<ReadyComponent />}
/>
```

2022-07-11 09:11 UTC, MOZGIII requested changes
I've thought about the design, and figured it wouldn't be fair to prioritise the component guard  or element guard as a default now, since we have to options. So, let's make it so there are two entities: ComponentGuard and ElementGuard. We shall build all the accompanying machinery atround each if them too.

2022-07-17 19:41 UTC, MOZGIII commented on packages/react/src/ComponentGuard.tsx
> +export type StateComponentGuardProps<
```suggestion
export type StateComponentProps<
```

2022-07-18 07:52 UTC, sesh92 commented on packages/react/src/ComponentGuard.tsx
> +export type StateComponentGuardProps<
https://github.com/MOZGIII/tagged-state/pull/2/commits/93a787de5e0b59733f11022acc744bfdd6a20abd

2022-07-18 14:10 UTC, MOZGIII commented on packages/react/src/createComponentGuard.tsx
> +function createComponentGuard<
```suggestion
function createContextComponentGuard <
```

2022-07-18 14:11 UTC, MOZGIII commented on packages/react/src/createElementGuard.tsx
> +function createElementGuard<
```suggestion
function createContextElementGuard<
```

2022-07-18 14:11 UTC, MOZGIII commented on packages/react/src/createElementGuard.tsx
> +export type ElementGuardProps<
```suggestion
export type ContextElementGuardProps<
```

2022-07-18 14:12 UTC, MOZGIII commented on packages/react/src/createElementGuard.tsx
> +  function ContextGuard(
```suggestion
  function ContextElementGuard(
```

2022-07-18 14:12 UTC, MOZGIII commented on packages/react/src/ElementGuard.tsx
> +export type StateElementGuardProps<
```suggestion
export type StateElementProps<
```

2022-07-19 14:56 UTC, MOZGIII approved these changes

2022-07-19 15:12 UTC, merged